Flatfield correction and metadata
czbiohub/microDL pull request #150
Opened 2022-05-02 21:08 UTC by jennyfolkesson

Here's another PR for you where:

* intensity values are computed after flatfield correction in preprocessing
* metadata is generated in preprocessing if no meta csv file is found in the input directory

After @JohannaRahm 's PR is merged with master I will rebase to master, then get the master_tests branch merged, then this one.

After this, I will start working on adding support for zarr input data.

2022-05-16 17:29 UTC, jennyfolkesson commented
@mattersoflight @smguo @JohannaRahm This PR is now ready for review. Thanks!

2022-05-31 01:17 UTC, smguo requested changes
Thanks for the PR @jennyfolkesson! The PR looks great. Please see my questions above.

2022-05-31 16:10 UTC, jennyfolkesson commented on micro_dl/utils/meta_utils.py
> +        mp_fn_args.append((im_path, ff_path, block_size, meta_row))
No that's not the behavior I want, thanks for catching that but. I'm now setting ff_path to None inside the for loop so no channels outside channel_ids flatfields should be messing up the calculations.

2022-05-31 19:53 UTC, smguo commented on micro_dl/utils/meta_utils.py
> +        mp_fn_args.append((im_path, ff_path, block_size, meta_row))
Setting ff_path to None inside the for loop makes sense to me. One more comment: It looks like flatfield correction share the parameter `channel_ids` as other preprocessing steps, but in most use cases we might apply flatfield correction to fluorescence channels but usually not to label-free channels. Should we make a separate `channel_ids` for flatfield correction? It can be done in the next PR if it requires more code changes.

2022-05-31 19:55 UTC, smguo approved these changes
Changes look good to me! I have one more comment but it can be addressed in the future PR. Feel free to merge the PR.

2022-05-31 19:56 UTC, jennyfolkesson commented on micro_dl/utils/meta_utils.py
> +        mp_fn_args.append((im_path, ff_path, block_size, meta_row))
Good point! Let's create an issue and I'll take care of it in a separate PR.

2022-05-31 19:56 UTC, merged